name: comparison
description: Run uuid-format-tester encoders on the draft test vectors.
publish_to: none
environment:
  sdk: ^3.5.1
dependencies:
  uuid: ^4.5.2
  base32: ^2.2.0
  base62x: ^0.2.3
  b: ^0.2.0
